name: Trigger CI

on:
  push:
    tags:
      - "v*.*.*" 

jobs:
  call-ci:
    uses: samanehghavami/Devops/.github/workflows/ci.yml@main
    with:
      registry: "192.168.1.200"
      image: "simple-npm-app"
      tag: ${{ github.ref_name }} 
    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
