name: Trigger Devops CI

on:
  push:
    tags:
      - '*'

jobs:
  trigger_ci:
    uses: samanehghavami/Devops/.github/workflows/ci.yml@ci
    with:
      repo: samanehghavami/simple-npm-project
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }} 
